In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv('SatImage.csv')
df.shape

(5803, 37)

In [3]:
y=df.iloc[:,-1]
unique, counts = np.unique(y, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'inlier': 5732, 'outlier': 71}

In [4]:
from sklearn import preprocessing
for x in df.columns:
    while df[x].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(df[x].values))
        df[x] = lbl.transform(list(df[x].values))

In [5]:
dataset=df.iloc[:,:-1]
data=dataset.copy()
y_true=df.iloc[:,-1]

In [6]:
from sklearn.preprocessing import StandardScaler
scp = StandardScaler()
scaled = scp.fit_transform(data)

In [7]:
from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster.fit_predict(scaled)

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [8]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37'],
      dtype='object')

In [9]:
df['cluster']=cluster.labels_
df['V37'] = pd.Categorical(df.V37)

df['cluster'] = pd.Series(cluster.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [11]:
#number of data objects in cluster A and cluster B
y1=df[['cluster']]
unique, counts = np.unique(y1, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 3771, 'B': 2032}

In [12]:
cluster_a=df.query('cluster=="A"')
cluster_b=df.query('cluster=="B"')

In [13]:
#iteration_1_cluster_candidate_A
y2=cluster_a[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 3700, 1: 71}

In [14]:
#iteration_1_cluster_candidate_A
y2=cluster_b[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2032}

In [15]:
#iteration_2
it_data1=cluster_a.iloc[:,:-2]
it_scaled1=scp.fit_transform(it_data1)
cluster1= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster1.fit_predict(it_scaled1)

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [16]:
#iteration_2_clustering
it_result1=cluster_a.iloc[:,:-1]
it_result1.reset_index(inplace=True)
it_result1['cluster'] = pd.Series(cluster1.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [17]:
#iteration_2_cluster_candidate
y2=it_result1[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 2258, 'B': 1513}

In [18]:
cluster_a1=it_result1.query('cluster=="A"')
cluster_b1=it_result1.query('cluster=="B"')

In [19]:
#iteration_2_cluster_candidate_A
y2=cluster_a1[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2198, 1: 60}

In [20]:
#iteration_2_cluster_candidate_B
y2=cluster_b1[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1502, 1: 11}

In [21]:
#iteration_3
it_data2=cluster_a1.iloc[:,:-2]
it_data2.drop(['index'],axis=1,inplace=True)
it_data2.reset_index(inplace=True)

In [22]:
#iteration_3
it_scaled2=scp.fit_transform(it_data2)
cluster2= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster2.fit_predict(it_scaled2)

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [23]:
#iteration_3_clustering
it_result2=cluster_a1.iloc[:,:-1]
it_result2.drop(['index'],axis=1,inplace=True)
it_result2.reset_index(inplace=True)
it_result2['cluster'] = pd.Series(cluster2.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [24]:
#iteration_2_cluster_candidate_B
y2=it_result2[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 2198, 'B': 60}

In [26]:
cluster_a2=it_result2.query('cluster=="A"')
cluster_b2=it_result2.query('cluster=="B"')

In [27]:
#iteration_3_cluster_candidate_A
y2=cluster_a2[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2198}

In [28]:
#iteration_3_cluster_candidate_A
y2=cluster_b2[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 60}

In [29]:
#iteration_5
it_data3=cluster_b1.iloc[:,:-2]
it_data3.drop(['index'],axis=1,inplace=True)
it_data3.reset_index(inplace=True)

In [30]:
#iteration_4
it_scaled3=scp.fit_transform(it_data3)
cluster3= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster3.fit_predict(it_scaled3)

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [31]:
#iteration_4_clustering
it_result4=cluster_b1.iloc[:,:-1]
it_result4.drop(['index'],axis=1,inplace=True)
it_result4.reset_index(inplace=True)
it_result4['cluster'] = pd.Series(cluster3.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [32]:
#iteration_2_cluster_candidate_B
y2=it_result4[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 984, 'B': 529}

In [33]:
cluster_a3=it_result4.query('cluster=="A"')
cluster_b3=it_result4.query('cluster=="B"')

In [34]:
#iteration_4_cluster_candidate_A
y2=cluster_a3[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 980, 1: 4}

In [35]:
y2=cluster_b3[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 522, 1: 7}

In [36]:
#iteration_
it_data4=cluster_b3.iloc[:,:-2]
it_data4.drop(['index'],axis=1,inplace=True)
it_data4.reset_index(inplace=True)

In [37]:
#iteration_4
it_scaled4=scp.fit_transform(it_data4)
cluster4= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster4.fit_predict(it_scaled4)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [38]:
#iteration_4_clustering
it_result5=cluster_b3.iloc[:,:-1]
it_result5.drop(['index'],axis=1,inplace=True)
it_result5.reset_index(inplace=True)
it_result5['cluster'] = pd.Series(cluster4.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [39]:
#iteration_2_cluster_candidate_B
y2=it_result5[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 381, 'B': 148}

In [40]:
cluster_a4=it_result5.query('cluster=="A"')
cluster_b4=it_result5.query('cluster=="B"')

In [41]:
#iteration_4_cluster_candidate_A
y2=cluster_a4[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 381}

In [42]:
#iteration_4_cluster_candidate_A
y2=cluster_b4[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 141, 1: 7}

In [43]:
#iteration_6
it_data5=cluster_b4.iloc[:,:-2]
it_data5.drop(['index'],axis=1,inplace=True)
it_data5.reset_index(inplace=True)

In [44]:
#iteration_4
it_scaled5=scp.fit_transform(it_data5)
cluster5= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster5.fit_predict(it_scaled5)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [45]:
#iteration_4_clustering
it_result6=cluster_b4.iloc[:,:-1]
it_result6.drop(['index'],axis=1,inplace=True)
it_result6.reset_index(inplace=True)
it_result6['cluster'] = pd.Series(cluster5.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [46]:
#iteration_2_cluster_candidate_B
y2=it_result6[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 129, 'B': 19}

In [47]:
cluster_a5=it_result6.query('cluster=="A"')
cluster_b5=it_result6.query('cluster=="B"')

In [48]:
#iteration_4_cluster_candidate_A
y2=cluster_a5[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 129}

In [49]:
#iteration_4_cluster_candidate_A
y2=cluster_b5[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 12, 1: 7}

In [50]:
#iteration_6
it_data6=cluster_b5.iloc[:,:-2]
it_data6.drop(['index'],axis=1,inplace=True)
it_data6.reset_index(inplace=True)

#iteration_4
it_scaled6=scp.fit_transform(it_data6)
cluster6= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster6.fit_predict(it_scaled6)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [51]:
#iteration_4_clustering
it_result7=cluster_b5.iloc[:,:-1]
it_result7.drop(['index'],axis=1,inplace=True)
it_result7.reset_index(inplace=True)
it_result7['cluster'] = pd.Series(cluster6.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [52]:
#iteration_2_cluster_candidate_B
y2=it_result7[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 16, 'B': 3}

In [53]:
cluster_a6=it_result7.query('cluster=="A"')
cluster_b6=it_result7.query('cluster=="B"')

In [54]:
#iteration_4_cluster_candidate_A
y2=cluster_a6[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 12, 1: 4}

In [55]:
#iteration_4_cluster_candidate_A
y2=cluster_b6[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 3}

In [56]:
#iteration_6
it_data7=cluster_a6.iloc[:,:-2]
it_data7.drop(['index'],axis=1,inplace=True)
it_data7.reset_index(inplace=True)

#iteration_4
it_scaled7=scp.fit_transform(it_data7)
cluster7= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster7.fit_predict(it_scaled7)

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [57]:
#iteration_4_clustering
it_result8=cluster_a6.iloc[:,:-1]
it_result8.drop(['index'],axis=1,inplace=True)
it_result8.reset_index(inplace=True)
it_result8['cluster'] = pd.Series(cluster7.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [58]:
#iteration_2_cluster_candidate_B
y2=it_result8[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 9, 'B': 7}

In [59]:
cluster_a7=it_result8.query('cluster=="A"')
cluster_b7=it_result8.query('cluster=="B"')

In [60]:
#iteration_4_cluster_candidate_A
y2=cluster_a7[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 5, 1: 4}

In [61]:
#iteration_4_cluster_candidate_A
y2=cluster_b7[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 7}

In [62]:
#iteration_6
it_data8=cluster_a7.iloc[:,:-2]
it_data8.drop(['index'],axis=1,inplace=True)
it_data8.reset_index(inplace=True)

#iteration_4
it_scaled8=scp.fit_transform(it_data8)
cluster8= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster8.fit_predict(it_scaled8)

array([0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [63]:
#iteration_4_clustering
it_result9=cluster_a7.iloc[:,:-1]
it_result9.drop(['index'],axis=1,inplace=True)
it_result9.reset_index(inplace=True)
it_result9['cluster'] = pd.Series(cluster8.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [64]:
#iteration_2_cluster_candidate_B
y2=it_result9[['cluster']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'A': 8, 'B': 1}

In [65]:
cluster_a8=it_result9.query('cluster=="A"')
cluster_b8=it_result9.query('cluster=="B"')

In [66]:
#iteration_4_cluster_candidate_A
y2=cluster_a8[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 4, 1: 4}

In [68]:
#iteration_4_cluster_candidate_A
y2=cluster_b8[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1}

In [69]:
#iteration_6
it_data9=cluster_a8.iloc[:,:-2]
it_data9.drop(['index'],axis=1,inplace=True)
it_data9.reset_index(inplace=True)

#iteration_4
it_scaled9=scp.fit_transform(it_data9)
cluster9= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster9.fit_predict(it_scaled9)

array([1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [70]:
#iteration_4_clustering
it_result10=cluster_a8.iloc[:,:-1]
it_result10.drop(['index'],axis=1,inplace=True)
it_result10.reset_index(inplace=True)
it_result10['cluster'] = pd.Series(cluster9.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [71]:
cluster_a9=it_result10.query('cluster=="A"')
cluster_b9=it_result10.query('cluster=="B"')

In [72]:
#iteration_4_cluster_candidate_A
y2=cluster_a9[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 4, 1: 1}

In [73]:
#iteration_4_cluster_candidate_A
y2=cluster_b9[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 3}

In [74]:
#iteration_6
it_data10=cluster_a9.iloc[:,:-2]
it_data10.drop(['index'],axis=1,inplace=True)
it_data10.reset_index(inplace=True)

#iteration_4
it_scaled10=scp.fit_transform(it_data10)
cluster10= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster10.fit_predict(it_scaled10)

array([0, 1, 0, 0, 1], dtype=int64)

In [75]:
#iteration_4_clustering
it_result11=cluster_a9.iloc[:,:-1]
it_result11.drop(['index'],axis=1,inplace=True)
it_result11.reset_index(inplace=True)
it_result11['cluster'] = pd.Series(cluster10.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [76]:
cluster_a10=it_result11.query('cluster=="A"')
cluster_b10=it_result11.query('cluster=="B"')

In [77]:
#iteration_4_cluster_candidate_A
y2=cluster_a10[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2, 1: 1}

In [78]:
#iteration_4_cluster_candidate_A
y2=cluster_b10[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2}

In [79]:
#iteration_6
it_data11=cluster_a10.iloc[:,:-2]
it_data11.drop(['index'],axis=1,inplace=True)
it_data11.reset_index(inplace=True)

#iteration_4
it_scaled11=scp.fit_transform(it_data11)
cluster11= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster11.fit_predict(it_scaled11)

array([1, 0, 0], dtype=int64)

In [80]:
#iteration_4_clustering
it_result12=cluster_a10.iloc[:,:-1]
it_result12.drop(['index'],axis=1,inplace=True)
it_result12.reset_index(inplace=True)
it_result12['cluster'] = pd.Series(cluster11.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [81]:
cluster_a11=it_result12.query('cluster=="A"')
cluster_b11=it_result12.query('cluster=="B"')

In [82]:
#iteration_4_cluster_candidate_A
y2=cluster_a11[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2}

In [83]:
#iteration_4_cluster_candidate_A
y2=cluster_b11[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 1}

In [84]:
#iteration_6
it_data12=cluster_a3.iloc[:,:-2]
it_data12.drop(['index'],axis=1,inplace=True)
it_data12.reset_index(inplace=True)

#iteration_4
it_scaled12=scp.fit_transform(it_data12)
cluster12= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster12.fit_predict(it_scaled12)

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [85]:
#iteration_4_clustering
it_result13=cluster_a3.iloc[:,:-1]
it_result13.drop(['index'],axis=1,inplace=True)
it_result13.reset_index(inplace=True)
it_result13['cluster'] = pd.Series(cluster12.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [86]:
cluster_a12=it_result13.query('cluster=="A"')
cluster_b12=it_result13.query('cluster=="B"')

In [87]:
#iteration_4_cluster_candidate_A
y2=cluster_a12[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 681, 1: 4}

In [88]:
#iteration_4_cluster_candidate_A
y2=cluster_b12[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 299}

In [89]:
#iteration_6
it_data13=cluster_a12.iloc[:,:-2]
it_data13.drop(['index'],axis=1,inplace=True)
it_data13.reset_index(inplace=True)

#iteration_4
it_scaled13=scp.fit_transform(it_data13)
cluster13= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster13.fit_predict(it_scaled13)

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [90]:
#iteration_4_clustering
it_result14=cluster_a12.iloc[:,:-1]
it_result14.drop(['index'],axis=1,inplace=True)
it_result14.reset_index(inplace=True)
it_result14['cluster'] = pd.Series(cluster13.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [91]:
cluster_a13=it_result14.query('cluster=="A"')
cluster_b13=it_result14.query('cluster=="B"')

In [92]:
#iteration_4_cluster_candidate_A
y2=cluster_a13[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 433}

In [93]:
#iteration_4_cluster_candidate_A
y2=cluster_b13[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 248, 1: 4}

In [94]:
#iteration_6
it_data14=cluster_b13.iloc[:,:-2]
it_data14.drop(['index'],axis=1,inplace=True)
it_data14.reset_index(inplace=True)

#iteration_4
it_scaled14=scp.fit_transform(it_data14)
cluster14= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster14.fit_predict(it_scaled14)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [95]:
#iteration_4_clustering
it_result15=cluster_b13.iloc[:,:-1]
it_result15.drop(['index'],axis=1,inplace=True)
it_result15.reset_index(inplace=True)
it_result15['cluster'] = pd.Series(cluster14.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [96]:
cluster_a14=it_result15.query('cluster=="A"')
cluster_b14=it_result15.query('cluster=="B"')

In [97]:
#iteration_4_cluster_candidate_A
y2=cluster_a14[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 192, 1: 4}

In [98]:
#iteration_4_cluster_candidate_A
y2=cluster_b14[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 56}

In [99]:
#iteration_6
it_data15=cluster_a14.iloc[:,:-2]
it_data15.drop(['index'],axis=1,inplace=True)
it_data15.reset_index(inplace=True)

#iteration_4
it_scaled15=scp.fit_transform(it_data15)
cluster15= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster15.fit_predict(it_scaled15)

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [100]:
#iteration_4_clustering
it_result16=cluster_a14.iloc[:,:-1]
it_result16.drop(['index'],axis=1,inplace=True)
it_result16.reset_index(inplace=True)
it_result16['cluster'] = pd.Series(cluster15.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [101]:
cluster_a15=it_result16.query('cluster=="A"')
cluster_b15=it_result16.query('cluster=="B"')

In [102]:
#iteration_4_cluster_candidate_A
y2=cluster_a15[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 179}

In [103]:
#iteration_4_cluster_candidate_A
y2=cluster_b15[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 13, 1: 4}

In [104]:
#iteration_6
it_data16=cluster_b15.iloc[:,:-2]
it_data16.drop(['index'],axis=1,inplace=True)
it_data16.reset_index(inplace=True)

#iteration_4
it_scaled16=scp.fit_transform(it_data16)
cluster16= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster16.fit_predict(it_scaled16)

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0], dtype=int64)

In [105]:
#iteration_4_clustering
it_result17=cluster_b15.iloc[:,:-1]
it_result17.drop(['index'],axis=1,inplace=True)
it_result17.reset_index(inplace=True)
it_result17['cluster'] = pd.Series(cluster16.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [106]:
cluster_a16=it_result17.query('cluster=="A"')
cluster_b16=it_result17.query('cluster=="B"')

In [107]:
#iteration_4_cluster_candidate_A
y2=cluster_a16[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 8, 1: 3}

In [108]:
#iteration_4_cluster_candidate_A
y2=cluster_b16[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 5, 1: 1}

In [109]:
#iteration_6
it_data17=cluster_a16.iloc[:,:-2]
it_data17.drop(['index'],axis=1,inplace=True)
it_data17.reset_index(inplace=True)

#iteration_4
it_scaled17=scp.fit_transform(it_data17)
cluster17= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster17.fit_predict(it_scaled17)

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [110]:
#iteration_4_clustering
it_result18=cluster_a16.iloc[:,:-1]
it_result18.drop(['index'],axis=1,inplace=True)
it_result18.reset_index(inplace=True)
it_result18['cluster'] = pd.Series(cluster17.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [111]:
cluster_a17=it_result18.query('cluster=="A"')
cluster_b17=it_result18.query('cluster=="B"')

In [112]:
#iteration_4_cluster_candidate_A
y2=cluster_a17[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 6, 1: 1}

In [113]:
#iteration_4_cluster_candidate_A
y2=cluster_b17[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2, 1: 2}

In [114]:
#iteration_6
it_data18=cluster_a17.iloc[:,:-2]
it_data18.drop(['index'],axis=1,inplace=True)
it_data18.reset_index(inplace=True)

#iteration_4
it_scaled18=scp.fit_transform(it_data18)
cluster18= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster18.fit_predict(it_scaled18)

array([0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [115]:
#iteration_4_clustering
it_result19=cluster_a17.iloc[:,:-1]
it_result19.drop(['index'],axis=1,inplace=True)
it_result19.reset_index(inplace=True)
it_result19['cluster'] = pd.Series(cluster18.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [116]:
cluster_a18=it_result19.query('cluster=="A"')
cluster_b18=it_result19.query('cluster=="B"')

In [117]:
#iteration_4_cluster_candidate_A
y2=cluster_b18[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1}

In [118]:
#iteration_4_cluster_candidate_A
y2=cluster_a18[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 5, 1: 1}

In [119]:
#iteration_6
it_data19=cluster_a18.iloc[:,:-2]
it_data19.drop(['index'],axis=1,inplace=True)
it_data19.reset_index(inplace=True)

#iteration_4
it_scaled19=scp.fit_transform(it_data19)
cluster19= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster19.fit_predict(it_scaled19)

array([0, 1, 1, 0, 1, 0], dtype=int64)

In [120]:
#iteration_4_clustering
it_result20=cluster_a18.iloc[:,:-1]
it_result20.drop(['index'],axis=1,inplace=True)
it_result20.reset_index(inplace=True)
it_result20['cluster'] = pd.Series(cluster19.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [121]:
cluster_a19=it_result20.query('cluster=="A"')
cluster_b19=it_result20.query('cluster=="B"')

In [122]:
#iteration_4_cluster_candidate_A
y2=cluster_a19[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2, 1: 1}

In [123]:
#iteration_4_cluster_candidate_A
y2=cluster_b19[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 3}

In [124]:
#iteration_6
it_data20=cluster_a19.iloc[:,:-2]
it_data20.drop(['index'],axis=1,inplace=True)
it_data20.reset_index(inplace=True)

#iteration_4
it_scaled20=scp.fit_transform(it_data20)
cluster20= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster20.fit_predict(it_scaled20)

array([1, 0, 0], dtype=int64)

In [125]:
#iteration_4_clustering
it_result21=cluster_a19.iloc[:,:-1]
it_result21.drop(['index'],axis=1,inplace=True)
it_result21.reset_index(inplace=True)
it_result21['cluster'] = pd.Series(cluster20.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [126]:
cluster_a20=it_result21.query('cluster=="A"')
cluster_b20=it_result21.query('cluster=="B"')

In [127]:
#iteration_4_cluster_candidate_A
y2=cluster_b20[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 1}

In [128]:
#iteration_4_cluster_candidate_A
y2=cluster_a20[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2}

In [129]:
#iteration_6
it_data21=cluster_b17.iloc[:,:-2]
it_data21.drop(['index'],axis=1,inplace=True)
it_data21.reset_index(inplace=True)

#iteration_4
it_scaled21=scp.fit_transform(it_data21)
cluster21= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster21.fit_predict(it_scaled21)

array([1, 0, 0, 0], dtype=int64)

In [130]:
#iteration_4_clustering
it_result22=cluster_b17.iloc[:,:-1]
it_result22.drop(['index'],axis=1,inplace=True)
it_result22.reset_index(inplace=True)
it_result22['cluster'] = pd.Series(cluster21.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [131]:
cluster_a21=it_result22.query('cluster=="A"')
cluster_b21=it_result22.query('cluster=="B"')

In [132]:
#iteration_4_cluster_candidate_A
y2=cluster_b21[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 1}

In [133]:
#iteration_4_cluster_candidate_A
y2=cluster_a21[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 2, 1: 1}

In [134]:
#iteration_6
it_data22=cluster_a21.iloc[:,:-2]
it_data22.drop(['index'],axis=1,inplace=True)
it_data22.reset_index(inplace=True)

#iteration_4
it_scaled22=scp.fit_transform(it_data22)
cluster22= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster22.fit_predict(it_scaled22)

array([0, 1, 0], dtype=int64)

In [135]:
#iteration_4_clustering
it_result23=cluster_a21.iloc[:,:-1]
it_result23.drop(['index'],axis=1,inplace=True)
it_result23.reset_index(inplace=True)
it_result23['cluster'] = pd.Series(cluster22.labels_).apply(lambda x:'A' if (x==0) else 'B')

In [136]:
cluster_a22=it_result23.query('cluster=="A"')
cluster_b22=it_result23.query('cluster=="B"')

In [137]:
#iteration_4_cluster_candidate_A
y2=cluster_b22[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1}

In [138]:
#iteration_4_cluster_candidate_A
y2=cluster_a22[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1, 1: 1}

In [139]:
#iteration_6
it_data23=cluster_a22.iloc[:,:-2]
it_data23.drop(['index'],axis=1,inplace=True)
it_data23.reset_index(inplace=True)

#iteration_4
it_scaled23=scp.fit_transform(it_data23)
cluster23= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster23.fit_predict(it_scaled23)

array([1, 0], dtype=int64)

In [140]:
#iteration_4_clustering
it_result24=cluster_a22.iloc[:,:-1]
it_result24.drop(['index'],axis=1,inplace=True)
it_result24.reset_index(inplace=True)
it_result24['cluster'] = pd.Series(cluster23.labels_).apply(lambda x:'A' if (x==0) else 'B')

cluster_a23=it_result24.query('cluster=="A"')
cluster_b23=it_result24.query('cluster=="B"')

In [141]:
#iteration_4_cluster_candidate_A
y2=cluster_a23[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1}

In [142]:
#iteration_4_cluster_candidate_A
y2=cluster_b23[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 1}

In [143]:
#iteration_6
it_data24=cluster_b16.iloc[:,:-2]
it_data24.drop(['index'],axis=1,inplace=True)
it_data24.reset_index(inplace=True)

#iteration_4
it_scaled24=scp.fit_transform(it_data24)
cluster24= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster24.fit_predict(it_scaled24)

array([1, 0, 1, 0, 0, 0], dtype=int64)

In [144]:
#iteration_4_clustering
it_result25=cluster_b16.iloc[:,:-1]
it_result25.drop(['index'],axis=1,inplace=True)
it_result25.reset_index(inplace=True)
it_result25['cluster'] = pd.Series(cluster24.labels_).apply(lambda x:'A' if (x==0) else 'B')

cluster_a24=it_result25.query('cluster=="A"')
cluster_b24=it_result25.query('cluster=="B"')

In [145]:
#iteration_4_cluster_candidate_A
y2=cluster_a24[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 4}

In [146]:
#iteration_4_cluster_candidate_A
y2=cluster_b24[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1, 1: 1}

In [147]:
#iteration_6
it_data25=cluster_b24.iloc[:,:-2]
it_data25.drop(['index'],axis=1,inplace=True)
it_data25.reset_index(inplace=True)

#iteration_4
it_scaled25=scp.fit_transform(it_data25)
cluster25= AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster25.fit_predict(it_scaled25)

array([1, 0], dtype=int64)

In [148]:
#iteration_4_clustering
it_result26=cluster_b24.iloc[:,:-1]
it_result26.drop(['index'],axis=1,inplace=True)
it_result26.reset_index(inplace=True)
it_result26['cluster'] = pd.Series(cluster25.labels_).apply(lambda x:'A' if (x==0) else 'B')

cluster_a25=it_result26.query('cluster=="A"')
cluster_b25=it_result26.query('cluster=="B"')

In [149]:
#iteration_4_cluster_candidate_A
y2=cluster_b25[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{1: 1}

In [150]:
#iteration_4_cluster_candidate_A
y2=cluster_a25[['V37']]
unique, counts = np.unique(y2, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{0: 1}